booking/urls.py
from django.urls import path
from booking import views

app_name = "booking"

urlpatterns = [
    path("check_room_availability/", views.check_room_availability, name="check_room_availability"),
    path("add_to_selection/", views.add_to_selection, name="add_to_selection"),
    
]

hotel/urls.py
from django.urls import path 
from hotel import views  

app_name = "hotel"

urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<slug>/", views.hotel_detail, name="hotel_detail"),
    path("detail/<slug:slug>/room_type/<rt_slug>/", views.room_type_detail, name="room_type_detail"),
    path("selected_rooms/", views.selected_rooms, name="selected_rooms"),
]

hotel_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # Custom urls
    path("", include("hotel.urls")),
    path("user/", include("userauths.urls")),
    path("booking/", include("booking.urls")),

    # CKEditor
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/models.py
from django.db import models
from django.utils.text import slugify
from django.utils.html import mark_safe

from userauths.models import User
from shortuuid.django_fields import ShortUUIDField
import shortuuid
from django_ckeditor_5.fields import CKEditor5Field
from taggit.managers import TaggableManager

HOTEL_STATUS = (
    ("Draft", "Draft"),
    ("Disabled", "Disabled"),
    ("Rejected", "Rejected"),
    ("In Review", "In Review"),
    ("Live", "Live"),
)

ICON_TYPE = (
    ('Bootstrap Icons', 'Bootstrap Icons'),
    ('Fontawesome Icons', 'Fontawesome Icons'),
    ('Box Icons', 'Box Icons'),
    ('Remi Icons', 'Remi Icons'),
    ('Flat Icons', 'Flat Icons'),
)

PAYMENT_STATUS = (
    ("paid", "Paid"),
    ("pending", "Pending"),
    ("processing", "Processing"),
    ("cancelled", "Cancelled"),
    ("initiated", 'Initiated'),
    ("failed", 'failed'),
    ("refunding", 'refunding'),
    ("refunded", 'refunded'),
    ("unpaid", 'unpaid'),
    ("expired", 'expired'),
)

class Hotel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = CKEditor5Field(null=True, blank=True, config_name='extends')
    image = models.FileField(upload_to="hotel_gallery")
    address = models.CharField(max_length=1000)
    mobile = models.CharField(max_length=20)
    email = models.EmailField(max_length=100)
    status = models.CharField(max_length=20, choices=HOTEL_STATUS, default="Live")

    tags = TaggableManager(blank=True)
    views = models.IntegerField(default=0)
    featured = models.BooleanField(default=False)
    hid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefghijklmnopqrstuvxyz")
    slug = models.SlugField(unique=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    # I am overriding the save method bcoz if a user saves the same name as another hotel we will get an error. So we want to fix it in the backend
    def save(self, *args, **kwargs):
        if self.slug == "" or self.slug == None:
            uuid_key = shortuuid.uuid
            uniqueid = uuid_key[:4]
            self.slug = slugify(self.name) + '-' + str(uniqueid.lower())

        super(Hotel, self).save(*args, **kwargs)

    def thumbnail(self):
        return mark_safe("<img src='%s' width='50' height='50' style='object-fit: cover; border-radius: 6px;' />" % (self.image.url))
    
    def hotel_gallery(self):
        return HotelGallery.objects.filter(hotel=self)
    
    def hotel_room_type(self):
        return RoomType.objects.filter(hotel=self)
    

class HotelGallery(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    image = models.FileField(upload_to="hotel_gallery")
    hgid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefghijklmnopqrstuvxyz")

    def __str__(self):
        return str(self.hotel.name)
    
    class Meta:
        verbose_name_plural = 'Hotel Gallery'

class HotelFeatures(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    icon_type = models.CharField(max_length=100, null=True, blank=True, choices=ICON_TYPE)
    icon = models.CharField(max_length=100, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    hfid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefghijklmnopqrstuvxyz")

    def __str__(self):
        return str(self.name)
    
    class Meta:
        verbose_name_plural = "Hotel Features"

class HotelFAQs(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    question = models.CharField(max_length=1000)
    answer = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    hfqid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefghijklmnopqrstuvxyz")

    def __str__(self):
        return str(self.question)
    
    class Meta:
        verbose_name_plural = "Hotel FAQs"

class RoomType(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    type = models.CharField(max_length=10)
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    number_of_beds = models.PositiveIntegerField(default=0) # It mustnt be negative thats why
    room_capacity = models.PositiveIntegerField(default=0)
    rtid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefghijklmnopqrstuvxyz")
    slug = models.SlugField(unique=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.type} - {self.hotel.name} - {self.price}"

    def rooms_count(self):
        return Room.objects.filter(room_type=self).count()
    
    class Meta:
        verbose_name_plural = 'Room Type'

    
    def save(self, *args, **kwargs):
        if self.slug == "" or self.slug == None:
            uuid_key = shortuuid.uuid()
            uniqueid = uuid_key[:4]
            self.slug = slugify(self.type) + "-" + str(uniqueid.lower())
            
        super(RoomType, self).save(*args, **kwargs) 


class Room(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    room_number = models.CharField(max_length=1000)
    is_available = models.BooleanField(default=True)
    rid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefghijklmnopqrstuvxyz")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.hotel.name} - {self.room_type.type} -  Room {self.room_number}"
    
    class Meta:
        verbose_name_plural = "Rooms"

    def price(self):
        return self.room_type.price
    
    def number_of_beds(self):
        return self.room_type.number_of_beds
    
class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    payment_status = models.CharField(max_length=100, choices=PAYMENT_STATUS, default="initiated")

    full_name = models.CharField(max_length=1000, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=1000, null=True, blank=True)
    
    hotel = models.ForeignKey(Hotel, on_delete=models.SET_NULL, null=True) # When Booking is deleted we want to keep information in the database
    room_type = models.ForeignKey(RoomType, on_delete=models.SET_NULL, null=True)
    room = models.ManyToManyField(Room)
    before_discount = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    total = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    saved = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    check_in_date = models.DateField()
    check_out_date = models.DateField()
    total_days = models.PositiveIntegerField(default=0)
    num_adults = models.PositiveIntegerField(default=1)
    num_children = models.PositiveIntegerField(default=0)
    checked_in = models.BooleanField(default=False)
    checked_out = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    checked_in_tracker = models.BooleanField(default=False, help_text="DO NOT CHECK THIS BOX")
    checked_out_tracker = models.BooleanField(default=False, help_text="DO NOT CHECK THIS BOX")
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    # coupons = models.ManyToManyField("hotel.Coupon", blank=True)
    stripe_payment_intent = models.CharField(max_length=1000,null=True, blank=True)
    success_id = ShortUUIDField(length=300, max_length=505, alphabet="abcdefghijklmnopqrstuvxyz1234567890")
    booking_id = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefghijklmnopqrstuvxyz")


    def __str__(self):
        return f"{self.booking_id}"
    
    def rooms(self):
        return self.room.all().count()
    
class ActivityLog(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    guest_out = models.DateTimeField()
    guest_in = models.DateTimeField()
    description = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.booking)
    
class StaffOnDuty(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    staff_id = models.CharField(null=True, blank=True, max_length=100)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.staff_id)
    

# class Coupon(models.Model):
#     code = models.CharField(max_length=1000)
#     type = models.CharField(max_length=100, choices=DISCOUNT_TYPE, default="Percentage")
#     discount = models.IntegerField(default=1, validators=[MinValueValidator(0), MaxValueValidator(100)])
#     redemption = models.IntegerField(default=0)
#     date = models.DateTimeField(auto_now_add=True)
#     active = models.BooleanField(default=True)
#     make_public = models.BooleanField(default=False)
#     valid_from = models.DateField()
#     valid_to = models.DateField()
#     cid = ShortUUIDField(length=10, max_length=25, alphabet="abcdefghijklmnopqrstuvxyz")

    
#     def __str__(self):
#         return self.code
    
#     class Meta:
#         ordering =['-id']


# class CouponUsers(models.Model):
#     coupon = models.ForeignKey(Coupon, on_delete=models.CASCADE)
#     booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    
#     full_name = models.CharField(max_length=1000)
#     email = models.CharField(max_length=1000)
#     mobile = models.CharField(max_length=1000)

#     def __str__(self):
#         return str(self.coupon.code)
    
#     class Meta:
#         ordering =['-id']


# class RoomServices(models.Model):
#     booking = models.ForeignKey(Booking, null=True, on_delete=models.CASCADE)

hotel/views.py
from django.shortcuts import render, redirect

from hotel.models import Hotel, Room, Booking, HotelGallery, HotelFeatures, HotelFAQs, RoomType, ActivityLog, StaffOnDuty
from django.contrib import messages

from datetime import datetime

# Create your views here.
def index(request):
    hotels = Hotel.objects.filter(status="Live") # Means only Hotels that are live 
    context = {
        "hotels": hotels
    }
    return render(request, "hotel/hotel.html", context)

def hotel_detail(request, slug):
    hotel = Hotel.objects.get(status="Live", slug=slug) #When you want to retrieve 1 item you use get but when you want to retrieve a list you use filter or all
    context = {
        "hotel":hotel,
    }

    return render(request, "hotel/hotel_detail.html", context)

def room_type_detail(request, slug, rt_slug):
    hotel = Hotel.objects.get(status="Live", slug=slug)
    room_type = RoomType.objects.get(hotel=hotel, slug=rt_slug)
    rooms = Room.objects.filter(room_type=room_type, is_available=True)

    context = {
        "hotel": hotel,
        "room_type": room_type,
        "rooms": rooms,
    }

    return render(request, "hotel/room_type_detail.html", context)

def selected_rooms(request):
    total_count = 0
    room_count = 0
    total_days = 0
    adult = 0
    children = 0
    checkin = ''
    checkout = ''

    # Check if 'selection_data_obj' is in session
    if 'selection_data_obj' in request.session:
        for h_id, item in request.session["selection_data_obj"].items():
            # Extract data from session
            id = int(item['hotel_id'])
            hotel_id = int(item['hotel_id'])
            checkin = item['checkin']
            checkout = item['checkout']
            adult = item["adult"]
            children = item["children"]
            room_type_ = item["room_type"]
            room_id = int(item["room_id"])

            room_type = RoomType.objects.get(id=room_type_)

            # Validate and parse dates
            date_format = "%Y-%m-%d"
            try:
                checkin_date = datetime.strptime(checkin, date_format) if checkin else None
                checkout_date = datetime.strptime(checkout, date_format) if checkout else None
            except ValueError as e:
                # Log the error and set dates to None or default values
                print(f"Error parsing date: {e}")
                checkin_date = checkout_date = None

            # Calculate total_days if both dates are valid
            if checkin_date and checkout_date:
                time_difference = checkout_date - checkin_date
                total_days = time_difference.days

            print("total_days=======", total_days)

    else:
        # Warn user and redirect if no selection data
        messages.warning(request, "No rooms in selection")
        return redirect("/")

    # Render the selected rooms page
    return render(request, "hotel/selected_rooms.html")

templates/hotel/room_type_detail.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<div id="titlebar" class="gradient">
    <div class="container">
    <div class="row">
        <div class="col-md-12">
        <h2>{{room_type.type}} Room</h2>
        <nav id="breadcrumbs">
            <ul>
            <li><p>{{rooms.count}} Available Rooms</p></li>
            </ul>
        </nav>
        </div>
    </div>
    </div>
</div>


<section class="fullwidth_block margin-top-0 padding-top-0 padding-bottom-50" data-background-color="#fff"> 
    <div class="container">
    <div class="row">
        <div class="col-md-12">
        <h3 class="headline_part centered margin-bottom-20">All Available Rooms<span>The {{ room_type.type }} room has {{ rooms.count }} available room(s)</span></h3>
        </div>
    </div>
    <div class="row">  
        <div class="col-lg-8 "> 
        
        {% for r in rooms %}
            <div class="plan featured col-md-4 col-sm-6 col-xs-12">
            <div class="utf_price_plan">
                <h3>Room No. {{ r.room_number }}</h3>
                <span class="value">${{r.room_type.price}}<span>/Per Night</span></span> 
            </div>
            <div class="utf_price_plan_features">
                <ul>
                <li>Beds: {{r.room_type.number_of_beds}} </li>
                <li>Room Capacity: {{r.room_type.room_capacity}}</li>
                </ul>
                <input type="hidden" class="room_id_{{r.id}}" value="{{r.id}}" id="room_id">
                <input type="hidden" class="room_number_{{r.id}}" value="{{r.room_number}}" id="room_number">
                <button class="button border add-to-selection" data-index="{{r.id}}"><i class="fas fa-shopping-cart"></i> Add To Selection</button> 
            </div>
            </div>
        {% endfor %}
        <input type="hidden" value="{{hotel.id}}" id="id">
        <input type="hidden" value="{{hotel.name}}" id="hotel_name">
        <input type="hidden" value="{{room_type.type}}" id="room_name">
        <input type="hidden" value="{{room_type.price}}" id="room_price">
        <input type="hidden" value="{{room_type.number_of_beds}}" id="number_of_beds">
        <input type="hidden" value="{{room_type.id}}" id="room_type">
        <input type="hidden" value="{{checkin}}" id="checkin">
        <input type="hidden" value="{{checkout}}" id="checkout">
        <input type="hidden" value="{{adult}}" id="adult">
        <input type="hidden" value="{{children}}" id="children">

        
        </div>  
        <div class="col-lg-4">
            <div class=" booking_widget_box" style="border: 1px dashed rgba(42, 1, 119, 0.61); padding: 14px; border-radius: 10px;">
            <h3><i class="fa fa-calendar"></i> Booking</h3>
            <form class="row with-forms margin-top-0" method="POST" action="">
                {% csrf_token %}
                <input type="hidden" value="{{hotel.id}}" name="hotel-id" id="">
                <div class="col-lg-12 col-md-12 select_date_box">
                    <label for="">Check-in Date</label>
                    <input type="date" id="date-picker" value="{{checkin}}" name="checkin" placeholder="Select Date">
                </div>
                <div class="col-lg-12 col-md-12 select_date_box">
                    <label for="">Check-out Date</label>
                    <input type="date" class="checkout_date" name="checkout" value="{{checkout}}"  placeholder="Select Date">
                </div>
                <div class="with-forms">
                    <div class="col-lg-12 col-md-12">
                        <a href="#">Guests <span class="qtyTotal" name="qtyTotal">1</span></a>
                        <div class="panel-dropdown-content">
                            <div class="qtyButtons">
                                <div class="qtyTitle">Adults</div>
                                <input type="text" name="adult" {% if adult == None %}value="1"{% else %}value="{{adult}}"{% endif %}>
                            </div>
                            <div class="qtyButtons">
                                <div class="qtyTitle">Childrens</div>
                                <input type="text" name="children" {% if children == None %}value="1"{% else %}value="{{children}}"{% endif %}>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="with-forms margin-top-30">
                    <div class="col-lg-12 col-md-12 ">
                        <a href="#">Select Room Type</a>
                        <select name="room-type" class="utf_chosen_select_single" required>
                            <!-- <option value="{{room_type|lower}}">{{room_type}}</option> -->
                            <option value="{{room_type|lower}}">{{room_type}}</option>

                            {% for r in hotel.hotel_room_types %}
                                <option value="{{r.slug}}">{{r.type}}</option>
                            {% endfor %}
                            </select>
                    </div>
                </div>
                
                <button type="submit" class="utf_progress_button button fullwidth_block margin-top-5">Check Availability</button>
            </form>
            <button class="like-button add_to_wishlist"><span class="like-icon"></span> Add to Wishlist</button>
            <div class="clearfix"></div>
            </div>
        </div>      
            
    </div>      
    </div>    
</section>

<script>
    $(document).ready(function(){
        
        var dateInput = $('#checkout_date');

        dateInput.on('change', function() {
            var selectedDate = dateInput.val();
            console.log('Selected date:', selectedDate);
        });
    })
</script>

{% endblock content %}

templates/hotel/selected_rooms.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<div id="main_wrapper" class="selection-list">

<div id="titlebar" class="gradient">
    <div class="container">
    <div class="row">
        <div class="col-md-12">
        <h2>All Room Selections</h2>
        <nav id="breadcrumbs">
            <ul>
            <li><a>Home</a></li>
            <li><a>Hotel</a></li>
            <li><a>Rooms</a></li>
            <li>My selected rooms</li>
            </ul>
        </nav>
        </div>
    </div>
    </div>
</div>

<div class="container margin-bottom-75">
    <div class="row">
    <div class="col-lg-8 col-md-8 utf_listing_payment_section">
        
        <div class="utf_booking_listing_section_form margin-bottom-40">
            <h3><i class="fas fa-bed"></i> Selected Rooms</h3>
            <div class="utf_listing_section">
                    <div class="utf_pricing_list_section">
                        <ul>
                            {% for id, item in data.items %}
                                <li>
                                    <h5>Room: {{item.room_name}}  <small><a style="cursor: pointer;" class="delete-item" data-item="{{ id }}"><i class="fas fa-trash" style="color: red;"></i></a></small> </h5>
                                    <p><strong>Beds :</strong> {{item.number_of_beds}}  </p>
                                    <span>${{item.room_price}} </span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
            </div>
        </div>
        <div class="utf_booking_listing_section_form margin-bottom-40">
            <h3><i class="fas fa-check-circle"></i> Update Selection</h3>
            <div class="utf_listing_section">
                    <div class="utf_pricing_list_section">
                    <form class="row with-forms margin-top-0" method="POST" action="{% url 'booking:check_room_availability' %}">
                        {% csrf_token %}
                        <input type="hidden" value="{{hotel.id}}" name="hotel-id" id="">
                        <div class="col-lg-12 col-md-12 select_date_box">
                            <label for="">Check-in Date</label>
                            <input type="date" id="date-picker" value="" name="checkin" placeholder="Select Date">
                        </div>
                        <div class="col-lg-12 col-md-12 select_date_box">
                            <label for="">Check-out Date</label>
                            <input type="date" name="checkout" value="" id="date-picker" placeholder="Select Date">
                        </div>
                        <div class="with-forms">
                            <div class="col-lg-12 col-md-12">
                                <a href="#">Guests <span class="qtyTotal" style="visibility: hidden;" name="qtyTotal"></span></a>
                                <div class="panel-dropdown-content">
                                    <div class="qtyButtons">
                                        <div class="qtyTitle">Adults</div>
                                        <input type="text" name="adult" {% if adult == None %}value="1"{% else %}value="{{adult}}"{% endif %}>
                                    </div>
                                    <div class="qtyButtons">
                                        <div class="qtyTitle">Childrens</div>
                                        <input type="text" name="children" {% if children == None %}value="1"{% else %}value="{{children}}"{% endif %}>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <a style="margin-top: 50px;">Select Room Type (*required) </a>
                        <select name="room-type">
                            <option value="">Select Room</option>
                            
                            {% for r in hotel.hotel_room_types %}
                                <option value="{{r.slug}}">{{r.type}}</option>
                            {% endfor %}
                        </select>
                    
                        <button type="submit" class="utf_progress_button button fullwidth_block margin-top-5"> <i class="fas fa-check-circle"></i> Update Selection </button>
                    </form>
                    </div>
            </div>
        </div>
            
    <form class="utf_booking_listing_section_form margin-bottom-40" method="POST">
        {% csrf_token %}
        <h3><i class="fas fa-user"></i> Billing Information</h3>
        <div class="row">
        <div class="col-md-12">
        <label>First Name</label>
        <input name="full_name" type="text" value="{{request.user.profile.full_name|title}}" placeholder="First Name">
        </div>
        <div class="col-md-6">
        <div class="medium-icons">
            <label>E-Mail</label>
            <input name="email" type="text" value="{{request.user.email}}" placeholder="Email">
        </div>
        </div>
        <div class="col-md-6">
        <div class="medium-icons">
            <label>Phone</label>
            <input name="phone" type="text" value="{{request.user.phone}}" placeholder="Phone">
        </div>
        </div>
        <div class="col-lg-12">
            <button type="submit" class="button utf_booking_confirmation_button margin-top-20 margin-bottom-10">Continue to checkout <i class="fas fa-right-arrow"></i></button> 		
        </div>
        </div>
        </form>

        
    </div>
    <div class="col-lg-4 col-md-4 margin-top-0 utf_listing_payment_section">
        <div class="utf_booking_listing_item_container compact utf_order_summary_widget_section">
        <div class="listing-item"> <img src="{{hotel.image.url}}" alt="">
            <div class="utf_listing_item_content">              
            <h3>{{hotel.name}}</h3>
            <span><i class="fa fa-map-marker"></i> The Ritz-Carlton, Hong Kong</span>
                        <span><i class="fa fa-phone"></i> (+15) 124-796-3633</span>											
            <div class="utf_star_rating_section" data-rating="4.5">
                <div class="utf_counter_star_rating">(18) Reviews</div>
            </div>
            </div>
        </div>
        </div>
        <div class="boxed-widget opening-hours summary margin-top-0">
        <h3><i class="fa fa-calendar-check-o"></i> Booking Summary</h3>
        <ul>
            <li>Check-in <span>{{checkin}}</span></li>
            <li>Check-out <span>{{checkout}}</span></li>            
            <li>Total Days <span>{{total_days}} Days</span></li>            
            <li>Adults <span>{{ adult }} Adult</span></li>
            <li>Children <span>{{ children }} Children</span></li>
                <li>V.A.T <span>$0.00</span></li>
            <li class="total-costs">Total Cost <span>${{total}}</span></li>
        </ul>
        </div>
    </div>
    </div>
</div>

</div>


{% endblock content %}