hotel/urls.py
from django.urls import path 
from hotel import views  

app_name = "hotel"

urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<slug>/", views.hotel_detail, name="hotel_detail"),
    path("detail/<slug:slug>/room_type/<rt_slug>/", views.room_type_detail, name="room_type_detail"),
    path("selected_rooms/", views.selected_rooms, name="selected_rooms"),
]

hotel_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # Custom urls
    path("", include("hotel.urls")),
    path("user/", include("userauths.urls")),
    path("booking/", include("booking.urls")),

    # CKEditor
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path 
from userauths import views  

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.RegisterView, name="sign-up"),
    path("sign-in/", views.loginViewTemp, name="sign-in"),
    path("sign-out/", views.LogOutView, name="sign-out"),
]

templates/partials/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="author" content="">
    <meta name="description" content="">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>:: Mzansi Luxuries ::</title>
    <base href="{% static '/' %}">

    <!-- Favicon -->
    <link rel="shortcut icon" href="images/mdvlogo.png">
    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
    <link rel="stylesheet" href="{% static 'css/mmenu.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" id="colors">
    <!-- Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" /> 


    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">  {% endcomment %}


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@7.2.96/css/materialdesignicons.min.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/remixicon-ligatures@2.5.0/fonts/remixicon.min.css">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script src="https://unpkg.com/sweetalert2@7.8.2/dist/sweetalert2.all.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://smtpjs.com/v3/smtp.js"></script> 
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,600,700,800&display=swap&subset=latin-ext,vietnamese" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700,800" rel="stylesheet" type="text/css">

    <script>{% static "scripts/custom.js" %}</script>
</head>

<body>

    <!-- Preloader Start -->
    {% comment %} <div class="preloader">
        <div class="utf-preloader">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div> {% endcomment %}
    <!-- Preloader End -->

    <!-- Wrapper -->
    <div id="main_wrapper">
        <header id="header_part" class="fullwidth">
            <div id="header">
                <div class="container">
                    <div class="utf_left_side">
                        <div id="logo">
                            <a href="/"><img src="{% static 'images/mdvlogo5.png' %}" alt="" id="logo"/></a>
                        </div>
                        <div class="mmenu-trigger">
                            <button class="hamburger utfbutton_collapse" type="button">
                                <span class="utf_inner_button_box">
                                    <span class="utf_inner_section"></span>
                                </span>
                            </button>
                        </div>
                        <nav id="navigation" class="style_one">
                            <ul id="responsive">
                                <li><a class="current" href="/">Home</a></li>
                                <li>
                                    <a href="#">Hotels</a>
                                    <ul>
                                        <li><a href="#">Jozi Hotel</a></li>
                                    </ul>
                                </li>
                                <li><a href="#">Dashboard</a></li>
                                <li><a href="#">Blog</a></li>
                            </ul>
                        </nav>
                        <div class="clearfix"></div>
                    </div>
                    <div class="utf_right_side">
                        <div class="header_widget">

                            {% if user.is_authenticated %}
                                <a href="{% url 'userauths:sign-in' %}" class="button border sign-in"><i class="fa fa-th"></i> Dashboard </a>
                                <a href="{% url 'userauths:sign-out' %}" class="button border sign-in"><i class="fa fa-sign-out"></i> Log Out</a>
                            {% else %}
                                <a href="{% url 'userauths:sign-up' %}" class="button border sign-in"><i class="fa fa-sign-in"></i> Register</a>
                                <a href="{% url 'userauths:sign-in' %}" class="button border sign-in"><i class="fa fa-sign-in"></i> Log In</a>
                            {% endif %}

                        </div>
                    </div>
                        
                    </div>
                </div>
            </div>
        </header>
        
        <div class="clearfix"></div>

{% block content %}

{% endblock content %}

<!-- Footer -->
<div id="footer" class="footer_sticky_part">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-12 col-xs-12">
                <h4>About Us</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</p>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-6">
                <h4>Useful Links</h4>
                <ul class="social_footer_link">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Listing</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-6">
                <h4>My Account</h4>
                <ul class="social_footer_link">
                    <li><a href="#">Dashboard</a></li>
                    <li><a href="#">Profile</a></li>
                    <li><a href="#">My Listing</a></li>
                    <li><a href="#">Favorites</a></li>
                </ul>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-6">
                <h4>Pages</h4>
                <ul class="social_footer_link">
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Our Partners</a></li>
                    <li><a href="#">How It Work</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-6">
                <h4>Help</h4>
                <ul class="social_footer_link">
                    <li><a href="#">Sign In</a></li>
                    <li><a href="#">Register</a></li>
                    <li><a href="#">Add Listing</a></li>
                    <li><a href="#">Pricing</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="footer_copyright_part">Copyright © 2024 All Rights Reserved. Methembe Vundla</div>
            </div>
        </div>
    </div>
</div>
<div id="bottom_backto_top"><a href="#"></a></div>
</div>

<script>
    {% for message in messages %}
        Swal.fire({
            icon:"{{message.tags}}",
            title: "{{message}}",
            text: "{{message.tags}}"
            timer: 4500
        })
    {% endfor %}
</script>



<!-- Scripts -->
<script src="{% static 'scripts/custom.js' %}"></script>
<script src="{% static 'scripts/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'scripts/chosen.min.js' %}"></script>
<script src="{% static 'scripts/slick.min.js' %}"></script>
<script src="{% static 'scripts/rangeslider.min.js' %}"></script>
<script src="{% static 'scripts/magnific-popup.min.js' %}"></script>
<script src="{% static 'scripts/jquery-ui.min.js' %}"></script>
<script src="{% static 'scripts/bootstrap-select.min.js' %}"></script>
<script src="{% static 'scripts/mmenu.js' %}"></script>
<script src="{% static 'scripts/tooltips.min.js' %}"></script>
<script src="{% static 'scripts/color_switcher.js' %}"></script>
<script src="{% static 'scripts/jquery_custom.js' %}"></script>
<script src="{% static 'scripts/typed.js' %}"></script>
<script src="{% static 'scripts/infobox.min.js' %}"></script> 
<script src="{% static 'scripts/markerclusterer.js' %}"></script> 
<script src="{% static 'scripts/maps.js' %}"></script>
<script src="{% static 'scripts/datedropper.js' %}"></script> 
<script src="{% static 'scripts/quantityButtons.js' %}"></script>
<script src="{% static 'scripts/moment.min.js' %}"></script>
<script src="{% static 'scripts/daterangepicker.js' %}"></script>
<script src="{% static 'scripts/moment.min.js' %}"></script>
<script src="{% static 'scripts/daterangepicker.js' %}"></script>

<script>
function initAutocomplete() {
    var input = document.getElementById('autocomplete-input');
    var autocomplete = new google.maps.places.Autocomplete(input);

    autocomplete.addListener('place_changed', function() {
        var place = autocomplete.getPlace();
        if (!place.geometry) {
            window.alert("No details available for input: '" + place.name + "'");
            return;
        }
    });

    if ($('.main-search-input-item')[0]) {
        setTimeout(function() {
            $(".pac-container").prependTo("#autocomplete-container");
        }, 300);
    }
}
</script>
<!-- Date Range Picker - docs: http://www.daterangepicker.com/ -->
<script src="{% static 'scripts/moment.min.js' %}"></script>
<script src="{% static 'scripts/daterangepicker.js' %}"></script>

<script>
$(function() {

    var start = moment().subtract(0, 'days');
    var end = moment().add(2, 'days');

    function cb(start, end) {
        $('#booking-date-search').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    }
    cb(start, end);
    $('#booking-date-search').daterangepicker({
        "opens": "right",
        "autoUpdateInput": true,
        "alwaysShowCalendars": true,
        startDate: start,
        endDate: end
    }, cb);

    cb(start, end);

});

// Calendar animation and visual settings
$('#booking-date-search').on('show.daterangepicker', function(ev, picker) {
    $('.daterangepicker').addClass('calendar-visible calendar-animated bordered-style');
    $('.daterangepicker').removeClass('calendar-hidden');
});
$('#booking-date-search').on('hide.daterangepicker', function(ev, picker) {
    $('.daterangepicker').removeClass('calendar-visible');
    $('.daterangepicker').addClass('calendar-hidden');
});

$(window).on('load', function() {
    $('#booking-date-search').val('');
});
</script>

<!-- Style Switcher -->
<div id="color_switcher_preview">
<h2>Choose Your Color <a href="#"><i class="fa fa-gear fa-spin (alias)"></i></a></h2>
<div>
    <ul class="colors" id="color1">
        <li><a href="#" class="stylesheet"></a></li>
        <li><a href="#" class="stylesheet_1"></a></li>
        <li><a href="#" class="stylesheet_2"></a></li>
        <li><a href="#" class="stylesheet_3"></a></li>
        <li><a href="#" class="stylesheet_4"></a></li>
        <li><a href="#" class="stylesheet_5"></a></li>
    </ul>
</div>
</div>
</body>

</html>